### ISSUE TITLE
Docstring field on all schema fields

### ISSUE THREAD

**Issue by mallyvai** [pyeve/cerberus#558]
Used Cerberus version / latest commit: …

- [ ] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Bug report / Feature request

We're a platform team using Cerberus schemas to help us validate and compile YAML that other engineers send us. We're exposing this YAML interface to the engineering organization organization at large, and are writing a parallel set of documentation around it to make usage instructions obvious. The docs simply replicate the Cerberus schema.yaml and add a few sentences to each. Instead, if docstrings were a valid field we could keep the source of truth in the schema.yaml and trivially generate documentation from the schema.yaml. Here's an example schema that would be helpful for us:

```
teams:
  type: dict
  docstring: "This field specifies a team->permission mapping for the entity. Example usage:
  teams:  
    infra-team: "admin"
    intern-team:    "read"
"
  keysrules:
    type: string
  valuesrules:
    type: string

```
