### ISSUE TITLE
Add "description" field to make schemas self-documenting

### ISSUE THREAD

**Issue by jhuitema** [pyeve/cerberus#589]
Used Cerberus version / latest commit: 1.1.0 (but I think this is valid in the newest versions too)

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

* As a _user of cerberus_ I want/need to be able to _specify a description of a field_, so that I can _communicate the intent of a field to future developers_.
* As a _user of cerberus_ I want/need to be able to _specify a description of a field_, so that I can _validate that the description is available for future developers_.
* **For bonus points**: As a _user of cerberus_ I want/need to be able to _require that all fields in a schema have a description_, so that I can _validate that the description is available for future developers_.
----

#### Feature request

Would it be possible to add a "description" field to the validation schema that can be used to document a field for a human reading the schema? That way we could better enforce that our schemas are documented within our company.

[JSONSchema support this concept](https://json-schema.org/understanding-json-schema/reference/generic.html#id2) but I'd rather use cerberus as I like it better 😛 

I was thinking it could look something like this:

```yaml
  id:
    description: The unique numeric identifier for the Asset
    type: integer
    required: true
    min: 1

  name:
    description: The name of the Asset
    type: string
    required: true
    empty: false
    regex: ^[a-z][a-z0-9]+$
```

Without this feature we are specifying the description as comments which can be easily lost or forgotten:

```yaml
  # The unique numeric identifier for the Asset
  id:
    type: integer
    required: true
    min: 1

  # The name of the Asset
  name:
    type: string
    required: true
    empty: false
    regex: ^[a-z][a-z0-9]+$
```
