### ISSUE TITLE
How to apply dependency validation in the same block ?

### ISSUE THREAD

**Issue by prk2331** [pyeve/cerberus#621]
@funkyfuture  sorry to tag you directly here
but i'm stuck in this from a long.

Split type dependency on cut off date
When split_type is "custom" then "cutoff_date" is required.

```
data_splitting:
  type: dict
  required: true
  schema:
    split_type:
      type: string
      allowed:
        - train_test
        - k_fold
        - custom
      required: true
    cutoff_date:
      type: string
      regex: "\\d{4}-\\d{2}-\\d{2}"
      required: false
      dependencies:
        split_type:
        - "custom"
```

Im getting below error

{'data_splitting': [{'cutoff_date': ["depends on these values: {'split_type': ['custom']}"]}]}

**Comment by prk2331** [comment]
Please guide

**Comment by prk2331** [comment]
this dependencies will work when you write the dependency for other field level
i mean to say that suppose if we write the "cutoff_date" in parallel to "data_splitting" then and only it will work

```
data_splitting:
  type: dict
  required: true
  schema:
    split_type:
      type: string
      allowed:
        - train_test
        - k_fold
        - custom
      required: true
cutoff_date:
  type: string
  regex: "\\d{4}-\\d{2}-\\d{2}"
  required: false
  dependencies:
    data_splitting.split_type:
    - "custom"
```

If field validations are on same block then it wont work as expected


Q2. if suppose user passed in the document 
split_type: k_fold
cutoff_date : "2024-09-09"

then how to bypass this validation ? how can i enforce this in the schema only that don't consider cutoff_date validation when split_type is not custom ? (without writing server side validations with functions)

Q3. In this schema how can i enforce the custom Error messages (without writing server side validations with functions) 

right now this error is coming
cutoff_date: depends on these values: {'data_splitting.split_type': ['custom']}

i want error like this (For split_type "custom" cutoff_date is required)  **Human Readable Error**
